version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
